# -*- mode: toml; -*-
# vim: set ft=toml:
# Everforest Medium
[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

[colors.normal]
black   = "#272e33"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#3d484d"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
