# -*- mode: toml; -*-
# vim: set ft=toml:
# Kanagawa Dragon
[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.normal]
black   = "#0d0c0c"
red     = "#c4746e"
green   = "#87a987"
yellow  = "#c4b28a"
blue    = "#658594"
magenta = "#938AA9"
cyan    = "#8ea4a2"
white   = "#a6a69c"

[colors.bright]
black   = "#282727"
red     = "#c4746e"
green   = "#87a987"
yellow  = "#c4b28a"
blue    = "#658594"
magenta = "#938AA9"
cyan    = "#8ea4a2"
white   = "#c5c9c5"
