# -*- mode: toml; -*-
# vim: set ft=toml:
# Tokyo Night Moon
[colors.primary]
background = "#222436"
foreground = "#c8d3f5"

[colors.normal]
black   = "#1e2030"
red     = "#ff757f"
green   = "#c3e88d"
yellow  = "#ffc777"
blue    = "#82aaff"
magenta = "#c099ff"
cyan    = "#86e1fc"
white   = "#828bb8"

[colors.bright]
black   = "#444a73"
red     = "#ff757f"
green   = "#c3e88d"
yellow  = "#ffc777"
blue    = "#82aaff"
magenta = "#c099ff"
cyan    = "#86e1fc"
white   = "#c8d3f5"
