# Dark Earth
set -g status-style "bg=#2e2b28,fg=#D7C484"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#2e2b28]#[bg=#B3854D]#[bold] ZOOM #[default],} #[fg=#3a3530]█#[fg=#D7C484,bg=#3a3530] #S #[fg=#3a3530,bg=#2e2b28]█#[default] "
set -g status-right " #[fg=#3a3530]█#[fg=#D7C484,bg=#3a3530]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#453f39]█#[fg=#D7C484,bg=#453f39] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#B3854D]█#[fg=#24211E,bg=#B3854D,bold] %l:%M%p "

set -g window-status-format "#[fg=#3a3530,bg=#2e2b28]█#[fg=#D7C484,bg=#3a3530] #I:#W #[bg=#2e2b28]#[fg=#3a3530]█"
set -g window-status-current-format "#[fg=#B3854D,bg=#2e2b28]█#[fg=#24211E,bg=#B3854D,bold] #I:#W #[bg=#2e2b28]#[fg=#B3854D]█"

set -g pane-border-style 'fg=#3a3530'
set -g pane-active-border-style 'fg=#B3854D,bold'
set -g mode-style 'bg=#3a3530,fg=#D7C484,bold'
set -g window-style 'bg=#24211E'
set -g window-active-style 'bg=#24211E'
set -g popup-style 'bg=#24211E'
set -g popup-border-style 'bg=#24211E,fg=#453f39'
set -g @theme_copy_mode_bg 'bg=#1a1714'
