# Everforest Soft
set -g status-style "bg=#3d464d,fg=#d3c6aa"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#3d464d]#[bg=#dbbc7f]#[bold] ZOOM #[default],} #[fg=#475258]█#[fg=#d3c6aa,bg=#475258] #S #[fg=#475258,bg=#3d464d]█#[default] "
set -g status-right " #[fg=#475258]█#[fg=#d3c6aa,bg=#475258]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#525c62]█#[fg=#d3c6aa,bg=#525c62] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#a7c080]█#[fg=#333c43,bg=#a7c080,bold] %l:%M%p "

set -g window-status-format "#[fg=#475258,bg=#3d464d]█#[fg=#d3c6aa,bg=#475258] #I:#W #[bg=#3d464d]#[fg=#475258]█"
set -g window-status-current-format "#[fg=#a7c080,bg=#3d464d]█#[fg=#333c43,bg=#a7c080,bold] #I:#W #[bg=#3d464d]#[fg=#a7c080]█"

set -g pane-border-style 'fg=#475258'
set -g pane-active-border-style 'fg=#a7c080,bold'
set -g mode-style 'bg=#475258,fg=#d3c6aa,bold'
set -g window-style 'bg=#333c43'
set -g window-active-style 'bg=#333c43'
set -g popup-style 'bg=#333c43'
set -g popup-border-style 'bg=#333c43,fg=#525c62'
set -g @theme_copy_mode_bg 'bg=#2a3138'
