# Everforest Medium
set -g status-style "bg=#374247,fg=#d3c6aa"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#374247]#[bg=#dbbc7f]#[bold] ZOOM #[default],} #[fg=#3d484d]█#[fg=#d3c6aa,bg=#3d484d] #S #[fg=#3d484d,bg=#374247]█#[default] "
set -g status-right " #[fg=#3d484d]█#[fg=#d3c6aa,bg=#3d484d]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#475258]█#[fg=#d3c6aa,bg=#475258] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#a7c080]█#[fg=#2d353b,bg=#a7c080,bold] %l:%M%p "

set -g window-status-format "#[fg=#3d484d,bg=#374247]█#[fg=#d3c6aa,bg=#3d484d] #I:#W #[bg=#374247]#[fg=#3d484d]█"
set -g window-status-current-format "#[fg=#a7c080,bg=#374247]█#[fg=#2d353b,bg=#a7c080,bold] #I:#W #[bg=#374247]#[fg=#a7c080]█"

set -g pane-border-style 'fg=#3d484d'
set -g pane-active-border-style 'fg=#a7c080,bold'
set -g mode-style 'bg=#3d484d,fg=#d3c6aa,bold'
set -g window-style 'bg=#2d353b'
set -g window-active-style 'bg=#2d353b'
set -g popup-style 'bg=#2d353b'
set -g popup-border-style 'bg=#2d353b,fg=#475258'
set -g @theme_copy_mode_bg 'bg=#242c31'
