# Gruvbox Light
set -g status-style "bg=colour223,fg=colour237"

set -g status-left "##{tmux_mode_indicator}##{?window_zoomed_flag, #[fg=colour223]#[bg=colour166]#[bold] ZOOM #[default],} #[fg=colour246]█#[fg=colour237,bg=colour246] ##S #[fg=colour246,bg=colour223]█#[default] "
set -g status-right " #[fg=colour246]█#[fg=colour237,bg=colour246]  ##(cd ##{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=colour248]█#[fg=colour237,bg=colour248] ##($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=colour166]█#[fg=colour223,bg=colour166,bold] %l:%M%p "

set -g window-status-format "#[fg=colour246,bg=colour223]█#[fg=colour237,bg=colour246] ##I:##W #[bg=colour223]#[fg=colour246]█"
set -g window-status-current-format "#[fg=colour166,bg=colour223]█#[fg=colour223,bg=colour166,bold] ##I:##W #[bg=colour223]#[fg=colour166]█"

set -g pane-border-style 'fg=colour246'
set -g pane-active-border-style 'fg=colour166,bold'
set -g mode-style 'bg=#d5c4a1,fg=#3c3836,bold'
set -g window-style 'bg=#f2e5bc'
set -g window-active-style 'bg=#fbf1c7'
set -g popup-style 'bg=#fbf1c7'
set -g popup-border-style 'bg=#fbf1c7,fg=#7c6f64'
