# Gruvbox Material (medium contrast)
set -g status-style "bg=#3c3836,fg=#d4be98"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#3c3836]#[bg=#d8a657]#[bold] ZOOM #[default],} #[fg=#504945]█#[fg=#d4be98,bg=#504945] #S #[fg=#504945,bg=#3c3836]█#[default] "
set -g status-right " #[fg=#504945]█#[fg=#d4be98,bg=#504945]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#665c54]█#[fg=#d4be98,bg=#665c54] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#d8a657]█#[fg=#282828,bg=#d8a657,bold] %l:%M%p "

set -g window-status-format "#[fg=#504945,bg=#3c3836]█#[fg=#d4be98,bg=#504945] #I:#W #[bg=#3c3836]#[fg=#504945]█"
set -g window-status-current-format "#[fg=#d8a657,bg=#3c3836]█#[fg=#282828,bg=#d8a657,bold] #I:#W #[bg=#3c3836]#[fg=#d8a657]█"

set -g pane-border-style 'fg=#504945'
set -g pane-active-border-style 'fg=#d8a657,bold'
set -g mode-style 'bg=#504945,fg=#ddc7a1,bold'
set -g window-style 'bg=#282828'
set -g window-active-style 'bg=#282828'
set -g popup-style 'bg=#282828'
set -g popup-border-style 'bg=#282828,fg=#665c54'
set -g @theme_copy_mode_bg 'bg=#1d2021'
