# Gruvbox Dark Hard
set -g status-style "bg=colour234,fg=colour223"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=colour234]#[bg=colour208]#[bold] ZOOM #[default],} #[fg=colour237]█#[fg=colour223,bg=colour237] #S #[fg=colour237,bg=colour234]█#[default] "
set -g status-right " #[fg=colour237]█#[fg=colour223,bg=colour237]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=colour239]█#[fg=colour223,bg=colour239] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=colour214]█#[fg=colour234,bg=colour214,bold] %l:%M%p "

set -g window-status-format "#[fg=colour237,bg=colour234]█#[fg=colour246,bg=colour237] #I:#W #[bg=colour234]#[fg=colour237]█"
set -g window-status-current-format "#[fg=colour214,bg=colour234]█#[fg=colour234,bg=colour214,bold] #I:#W #[bg=colour234]#[fg=colour214]█"

set -g pane-border-style 'fg=colour237'
set -g pane-active-border-style 'fg=colour208,bold'
set -g mode-style 'bg=#1d2021,fg=#ebdbb2,bold'
set -g window-style 'bg=#1d2021'
set -g window-active-style 'bg=#1d2021'
set -g popup-style 'bg=#1d2021'
set -g popup-border-style 'bg=#1d2021,fg=#a89984'
set -g @theme_copy_mode_bg 'bg=#141617'
