# Gruvbox Dark
set -g status-style "bg=colour235,fg=colour223"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=colour235]#[bg=colour208]#[bold] ZOOM #[default],} #[fg=colour239]█#[fg=colour223,bg=colour239] #S #[fg=colour239,bg=colour235]█#[default] "
set -g status-right " #[fg=colour239]█#[fg=colour223,bg=colour239]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=colour241]█#[fg=colour223,bg=colour241] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=colour214]█#[fg=colour235,bg=colour214,bold] %l:%M%p "

set -g window-status-format "#[fg=colour239,bg=colour235]█#[fg=colour246,bg=colour239] #I:#W #[bg=colour235]#[fg=colour239]█"
set -g window-status-current-format "#[fg=colour214,bg=colour235]█#[fg=colour235,bg=colour214,bold] #I:#W #[bg=colour235]#[fg=colour214]█"

set -g pane-border-style 'fg=colour137'
set -g pane-active-border-style 'fg=colour208,bold'
set -g mode-style 'bg=#32302f,fg=#ebdbb2,bold'
set -g window-style 'bg=#32302f'
set -g window-active-style 'bg=#282828'
set -g popup-style 'bg=#282828'
set -g popup-border-style 'bg=#282828,fg=#a89984'
set -g @theme_copy_mode_bg 'bg=#1d2021'
