# Gruvbox Material Hard
set -g status-style "bg=#282828,fg=#d4be98"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#282828]#[bg=#d8a657]#[bold] ZOOM #[default],} #[fg=#3c3836]█#[fg=#d4be98,bg=#3c3836] #S #[fg=#3c3836,bg=#282828]█#[default] "
set -g status-right " #[fg=#3c3836]█#[fg=#d4be98,bg=#3c3836]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#504945]█#[fg=#d4be98,bg=#504945] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#d8a657]█#[fg=#1d2021,bg=#d8a657,bold] %l:%M%p "

set -g window-status-format "#[fg=#3c3836,bg=#282828]█#[fg=#d4be98,bg=#3c3836] #I:#W #[bg=#282828]#[fg=#3c3836]█"
set -g window-status-current-format "#[fg=#d8a657,bg=#282828]█#[fg=#1d2021,bg=#d8a657,bold] #I:#W #[bg=#282828]#[fg=#d8a657]█"

set -g pane-border-style 'fg=#3c3836'
set -g pane-active-border-style 'fg=#d8a657,bold'
set -g mode-style 'bg=#3c3836,fg=#ddc7a1,bold'
set -g window-style 'bg=#1d2021'
set -g window-active-style 'bg=#1d2021'
set -g popup-style 'bg=#1d2021'
set -g popup-border-style 'bg=#1d2021,fg=#504945'
set -g @theme_copy_mode_bg 'bg=#141617'
