# Gruvbox Material Soft
set -g status-style "bg=#45403d,fg=#d4be98"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#45403d]#[bg=#d8a657]#[bold] ZOOM #[default],} #[fg=#534f4c]█#[fg=#d4be98,bg=#534f4c] #S #[fg=#534f4c,bg=#45403d]█#[default] "
set -g status-right " #[fg=#534f4c]█#[fg=#d4be98,bg=#534f4c]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#665c54]█#[fg=#d4be98,bg=#665c54] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#d8a657]█#[fg=#32302f,bg=#d8a657,bold] %l:%M%p "

set -g window-status-format "#[fg=#534f4c,bg=#45403d]█#[fg=#d4be98,bg=#534f4c] #I:#W #[bg=#45403d]#[fg=#534f4c]█"
set -g window-status-current-format "#[fg=#d8a657,bg=#45403d]█#[fg=#32302f,bg=#d8a657,bold] #I:#W #[bg=#45403d]#[fg=#d8a657]█"

set -g pane-border-style 'fg=#534f4c'
set -g pane-active-border-style 'fg=#d8a657,bold'
set -g mode-style 'bg=#534f4c,fg=#ddc7a1,bold'
set -g window-style 'bg=#32302f'
set -g window-active-style 'bg=#32302f'
set -g popup-style 'bg=#32302f'
set -g popup-border-style 'bg=#32302f,fg=#665c54'
set -g @theme_copy_mode_bg 'bg=#282828'
