# Kanagawa Dragon
set -g status-style "bg=#282727,fg=#c5c9c5"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#282727]#[bg=#c4b28a]#[bold] ZOOM #[default],} #[fg=#1d1c1c]█#[fg=#c5c9c5,bg=#1d1c1c] #S #[fg=#1d1c1c,bg=#282727]█#[default] "
set -g status-right " #[fg=#1d1c1c]█#[fg=#c5c9c5,bg=#1d1c1c]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#393938]█#[fg=#c5c9c5,bg=#393938] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#658594]█#[fg=#181616,bg=#658594,bold] %l:%M%p "

set -g window-status-format "#[fg=#1d1c1c,bg=#282727]█#[fg=#a6a69c,bg=#1d1c1c] #I:#W #[bg=#282727]#[fg=#1d1c1c]█"
set -g window-status-current-format "#[fg=#658594,bg=#282727]█#[fg=#181616,bg=#658594,bold] #I:#W #[bg=#282727]#[fg=#658594]█"

set -g pane-border-style 'fg=#282727'
set -g pane-active-border-style 'fg=#658594,bold'
set -g mode-style 'bg=#282727,fg=#c5c9c5,bold'
set -g window-style 'bg=#181616'
set -g window-active-style 'bg=#181616'
set -g popup-style 'bg=#181616'
set -g popup-border-style 'bg=#181616,fg=#393938'
set -g @theme_copy_mode_bg 'bg=#0d0c0c'
