# Kanagawa Wave
set -g status-style "bg=#2a2a37,fg=#DCD7BA"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#2a2a37]#[bg=#E6C384]#[bold] ZOOM #[default],} #[fg=#363646]█#[fg=#DCD7BA,bg=#363646] #S #[fg=#363646,bg=#2a2a37]█#[default] "
set -g status-right " #[fg=#363646]█#[fg=#DCD7BA,bg=#363646]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#54546D]█#[fg=#DCD7BA,bg=#54546D] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#7E9CD8]█#[fg=#1F1F28,bg=#7E9CD8,bold] %l:%M%p "

set -g window-status-format "#[fg=#363646,bg=#2a2a37]█#[fg=#C8C093,bg=#363646] #I:#W #[bg=#2a2a37]#[fg=#363646]█"
set -g window-status-current-format "#[fg=#7E9CD8,bg=#2a2a37]█#[fg=#1F1F28,bg=#7E9CD8,bold] #I:#W #[bg=#2a2a37]#[fg=#7E9CD8]█"

set -g pane-border-style 'fg=#363646'
set -g pane-active-border-style 'fg=#7E9CD8,bold'
set -g mode-style 'bg=#363646,fg=#DCD7BA,bold'
set -g window-style 'bg=#1F1F28'
set -g window-active-style 'bg=#1F1F28'
set -g popup-style 'bg=#1F1F28'
set -g popup-border-style 'bg=#1F1F28,fg=#54546D'
set -g @theme_copy_mode_bg 'bg=#16161D'
