# Nord Light
set -g status-style "bg=#d8dee9,fg=#2e3440"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#d8dee9]#[bg=#5e81ac]#[bold] ZOOM #[default],} #[fg=#aebacf]█#[fg=#2e3440,bg=#aebacf] #S #[fg=#aebacf,bg=#d8dee9]█#[default] "
set -g status-right " #[fg=#aebacf]█#[fg=#2e3440,bg=#aebacf]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#c4cdd9]█#[fg=#2e3440,bg=#c4cdd9] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#5e81ac]█#[fg=#eceff4,bg=#5e81ac,bold] %l:%M%p "

set -g window-status-format "#[fg=#aebacf,bg=#d8dee9]█#[fg=#2e3440,bg=#aebacf] #I:#W #[bg=#d8dee9]#[fg=#aebacf]█"
set -g window-status-current-format "#[fg=#5e81ac,bg=#d8dee9]█#[fg=#eceff4,bg=#5e81ac,bold] #I:#W #[bg=#d8dee9]#[fg=#5e81ac]█"

set -g pane-border-style 'fg=#aebacf'
set -g pane-active-border-style 'fg=#5e81ac,bold'
set -g mode-style 'bg=#c4cdd9,fg=#2e3440,bold'
set -g window-style 'bg=#e5e9f0'
set -g window-active-style 'bg=#eceff4'
set -g popup-style 'bg=#eceff4'
set -g popup-border-style 'bg=#eceff4,fg=#aebacf'
