# Nordic
set -g status-style "bg=#2e3440,fg=#d8dee9"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#2e3440]#[bg=#ebcb8b]#[bold] ZOOM #[default],} #[fg=#3b4252]█#[fg=#d8dee9,bg=#3b4252] #S #[fg=#3b4252,bg=#2e3440]█#[default] "
set -g status-right " #[fg=#3b4252]█#[fg=#d8dee9,bg=#3b4252]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#434c5e]█#[fg=#d8dee9,bg=#434c5e] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#81a1c1]█#[fg=#242933,bg=#81a1c1,bold] %l:%M%p "

set -g window-status-format "#[fg=#3b4252,bg=#2e3440]█#[fg=#d8dee9,bg=#3b4252] #I:#W #[bg=#2e3440]#[fg=#3b4252]█"
set -g window-status-current-format "#[fg=#81a1c1,bg=#2e3440]█#[fg=#242933,bg=#81a1c1,bold] #I:#W #[bg=#2e3440]#[fg=#81a1c1]█"

set -g pane-border-style 'fg=#3b4252'
set -g pane-active-border-style 'fg=#81a1c1,bold'
set -g mode-style 'bg=#3b4252,fg=#eceff4,bold'
set -g window-style 'bg=#242933'
set -g window-active-style 'bg=#242933'
set -g popup-style 'bg=#242933'
set -g popup-border-style 'bg=#242933,fg=#4c566a'
set -g @theme_copy_mode_bg 'bg=#1c2028'
