# Tokyo Night
set -g status-style "bg=#1f2335,fg=#c0caf5"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#1f2335]#[bg=#e0af68]#[bold] ZOOM #[default],} #[fg=#292e42]█#[fg=#c0caf5,bg=#292e42] #S #[fg=#292e42,bg=#1f2335]█#[default] "
set -g status-right " #[fg=#292e42]█#[fg=#c0caf5,bg=#292e42]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#3b4261]█#[fg=#c0caf5,bg=#3b4261] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#7aa2f7]█#[fg=#1a1b26,bg=#7aa2f7,bold] %l:%M%p "

set -g window-status-format "#[fg=#292e42,bg=#1f2335]█#[fg=#a9b1d6,bg=#292e42] #I:#W #[bg=#1f2335]#[fg=#292e42]█"
set -g window-status-current-format "#[fg=#7aa2f7,bg=#1f2335]█#[fg=#1a1b26,bg=#7aa2f7,bold] #I:#W #[bg=#1f2335]#[fg=#7aa2f7]█"

set -g pane-border-style 'fg=#292e42'
set -g pane-active-border-style 'fg=#7aa2f7,bold'
set -g mode-style 'bg=#292e42,fg=#c0caf5,bold'
set -g window-style 'bg=#1a1b26'
set -g window-active-style 'bg=#1a1b26'
set -g popup-style 'bg=#1a1b26'
set -g popup-border-style 'bg=#1a1b26,fg=#414868'
