# Tokyo Night Storm
set -g status-style "bg=#2c3158,fg=#c0caf5"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#2c3158]#[bg=#e0af68]#[bold] ZOOM #[default],} #[fg=#343b6e]█#[fg=#c0caf5,bg=#343b6e] #S #[fg=#343b6e,bg=#2c3158]█#[default] "
set -g status-right " #[fg=#343b6e]█#[fg=#c0caf5,bg=#343b6e]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#3d4680]█#[fg=#c0caf5,bg=#3d4680] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#7aa2f7]█#[fg=#24283b,bg=#7aa2f7,bold] %l:%M%p "

set -g window-status-format "#[fg=#343b6e,bg=#2c3158]█#[fg=#a9b1d6,bg=#343b6e] #I:#W #[bg=#2c3158]#[fg=#343b6e]█"
set -g window-status-current-format "#[fg=#7aa2f7,bg=#2c3158]█#[fg=#24283b,bg=#7aa2f7,bold] #I:#W #[bg=#2c3158]#[fg=#7aa2f7]█"

set -g pane-border-style 'fg=#343b6e'
set -g pane-active-border-style 'fg=#7aa2f7,bold'
set -g mode-style 'bg=#343b6e,fg=#c0caf5,bold'
set -g window-style 'bg=#24283b'
set -g window-active-style 'bg=#24283b'
set -g popup-style 'bg=#24283b'
set -g popup-border-style 'bg=#24283b,fg=#414868'
set -g @theme_copy_mode_bg 'bg=#1d2027'
