# Tokyo Night Moon
set -g status-style "bg=#2d3354,fg=#c8d3f5"

set -g status-left "#{tmux_mode_indicator}#{?window_zoomed_flag, #[fg=#2d3354]#[bg=#ffc777]#[bold] ZOOM #[default],} #[fg=#353c62]█#[fg=#c8d3f5,bg=#353c62] #S #[fg=#353c62,bg=#2d3354]█#[default] "
set -g status-right " #[fg=#353c62]█#[fg=#c8d3f5,bg=#353c62]  #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-') #[fg=#3e4570]█#[fg=#c8d3f5,bg=#3e4570] #($HOME/code/scripts-private/bin/system-state-check --tmux) #[fg=#82aaff]█#[fg=#222436,bg=#82aaff,bold] %l:%M%p "

set -g window-status-format "#[fg=#353c62,bg=#2d3354]█#[fg=#828bb8,bg=#353c62] #I:#W #[bg=#2d3354]#[fg=#353c62]█"
set -g window-status-current-format "#[fg=#82aaff,bg=#2d3354]█#[fg=#222436,bg=#82aaff,bold] #I:#W #[bg=#2d3354]#[fg=#82aaff]█"

set -g pane-border-style 'fg=#353c62'
set -g pane-active-border-style 'fg=#82aaff,bold'
set -g mode-style 'bg=#353c62,fg=#c8d3f5,bold'
set -g window-style 'bg=#222436'
set -g window-active-style 'bg=#222436'
set -g popup-style 'bg=#222436'
set -g popup-border-style 'bg=#222436,fg=#444a73'
set -g @theme_copy_mode_bg 'bg=#1e2030'
