---
- name: Install kanata launchd daemon
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/.config/kanata/com.kanata.plist"
    dest: /Library/LaunchDaemons/com.kanata.plist
    owner: root
    group: wheel
    mode: '0644'
  register: kanata_plist

- name: Reload kanata launchd daemon if plist changed
  become: yes
  shell: |
    launchctl unload /Library/LaunchDaemons/com.kanata.plist 2>/dev/null || true
    launchctl load /Library/LaunchDaemons/com.kanata.plist
  when: kanata_plist.changed
  changed_when: kanata_plist.changed
